# Generated by Django 2.0.2 on 2018-03-17 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_create_table-course_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselocation',
            name='address',
        ),
        migrations.AddField(
            model_name='courselocation',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courselocation',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courselocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='courselocation',
            name='fax',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Must enter the phone number using an international format up to 15 digits. e.g. +18135550060 for a US country code (1) and area code (813)', regex='^\\+?\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='courselocation',
            name='state_province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courselocation',
            name='street_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courselocation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='courselocation',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Must enter the phone number using an international format up to 15 digits. e.g. +18135550060 for a US country code (1) and area code (813)', regex='^\\+?\\d{8,15}$')]),
        ),
    ]
