# Generated by Django 2.0.2 on 2018-03-18 02:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_create_table-courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('state_province', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Must enter the phone number using an international format up to 15 digits. e.g. +18135550060 for a US country code (1) and area code (813)', regex='^\\+?\\d{8,15}$')])),
                ('fax', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Must enter the phone number using an international format up to 15 digits. e.g. +18135550060 for a US country code (1) and area code (813)', regex='^\\+?\\d{8,15}$')])),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=20)),
                ('comments', models.TextField(blank=True, verbose_name='registration comments')),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('credit', 'credit card'), ('check', 'check'), ('po', 'purchase order'), ('phone', 'pay by phone')], max_length=6)),
                ('reference_type', models.CharField(choices=[('post', 'postcard'), ('email', 'email campaign'), ('search', 'google'), ('rec', 'recommendation')], max_length=6)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Course')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
